app/admin/views/article.py
# -*- coding: utf-8 -*- 
# Created by xuannan on 2019-01-26.
__author__ = 'Allen xu'
from flask import  request,jsonify,render_template
from flask_login import login_required

from app.admin.forms import ArticleForm
from app.admin.views.base import op_log,auth_required
from app.expand.utils import object_to_dict,build_tree
from app.models import Article,Crud,Category,Tag,TagRelation,and_
from .. import admin


# 添加文章
@admin.route("/article/add", methods=['POST'])
@login_required
@auth_required
def article_add():
    data = request.form
    form = ArticleForm(data)
    if form.validate():
        # 先添加产品信息  
        article_data = Crud.add(Article,data)
        if article_data:
            # 如果有标签信息，根据产品的id和标签ID保存关联的标签数据
            if data['tags']:
                tags = data['tags'].split(',') 
                tag_data = [TagRelation(
                    tag_type = 2,
                    relation_id = article_data.id,
                    tag_id =v
                ) for v in tags]
                Crud.add_all(tag_data)
            op_log("添加文章-%s" % article_data.title)
            return {"code": 1, "msg": "添加成功"}
        return {"code": 0, "msg": '添加失败，系统错误'}
    return {"code": 0, "msg": form.get_errors()}


# 文章列表
@admin.route("/article/list", methods=['GET'])
@login_required
@auth_required
def article_list():
    category_id = None
    page = 1
    search = ''
    if request.args.get('category_id'):
        category_id = int(request.args.get('category_id'))
    if request.args.get('page'):
        page = int(request.args.get('page'))
    if request.args.get('search'):
        search = request.args.get('search')
    #产品可用标签
    tag_data = Crud.get_data(Tag)
    #栏目树
    category_data = Crud.get_data(Category, Category.sort.desc())
    category_tree = build_tree(category_data, 0, 0)
    #产品栏目
    article_category = [v  for v in category_tree if v['type'] == 2 or v['type'] == 3 ]
    if category_id == None:
        article_data = Crud.search_data_paginate(Article,Article.title.like("%" + search + "%"),Article.sort.desc(),page,10)
    else:
        article_data = Crud.search_data_paginate(Article,and_(Article.category_id == category_id,Article.title.like("%" + search + "%")),Article.sort.desc(),page,10)
    return render_template("admin/article/article_list.html",
                           category_id=category_id,
                           article_data=article_data,
                           article_category = article_category,
                           tag_data = tag_data,
                           )


# 修改文章
@admin.route("/article/edit", methods=['GET', 'PUT'])
@login_required
@auth_required
def article_edit():
    if request.method == 'GET':
        getdata = request.args
        data = Crud.get_data_by_id(Article, getdata["id"])
        article_data = object_to_dict(data)
        #替换掉产品数据里面的TAGS
        tags = Crud.search_data(TagRelation,and_(TagRelation.relation_id==getdata["id"] , TagRelation.tag_type == 2),'create_time')
        if tags:
            article_data['tags'] = [v.tag_id for v in tags]
        return {"code": 1, "data": article_data}
    elif request.method == "PUT":
        data = request.form
        form = ArticleForm(data)
        if form.validate():
            #移除已保存的tag
            tags = Crud.search_data(TagRelation,and_(TagRelation.relation_id==data["id"] , TagRelation.tag_type == 2),'create_time')
            if tags:
                del_tags = Crud.clean_all(tags)
            #保存修改后的信息
            result = Crud.update(Article,data)
            # 如果有标签信息，根据产品的id和标签ID保存关联的标签数据
            if data['tags']:
                tags = data['tags'].split(',') 
                tag_data = [TagRelation(
                    tag_type = 2,
                    relation_id = data["id"],
                    tag_id =v
                ) for v in tags]
                Crud.add_all(tag_data)
            if result:
                op_log("修改文章 #%s" %  data["id"])
                return {"code": 1, "msg": '修改成功'}
            return {"code": 0, "msg": '修改失败，系统错误'} 
        return {"code": 0, "msg": form.get_errors()}



# 删除文章
@admin.route("/article/del", methods=['DELETE'])
@login_required
@auth_required
def article_del():
    deldata = request.form
    data = Article.query.filter_by(id=deldata['id']).first_or_404()
    result = Crud.delete(data)
    if result:
        op_log("删除文章-%s" % data.title)
        return {"code": 1, "msg": '删除成功'}
    return {"code": 0, "msg": '删除失败'}    

app/admin/views/product.py
# -*- coding: utf-8 -*- 
# Created by xuannan on 2019-01-26.
__author__ = 'Allen xu'
from flask import  request,jsonify,render_template
from flask_login import login_required
from app.admin.forms import ProductForm
from app.admin.views.base import op_log,auth_required
from app.expand.utils import object_to_dict,build_tree
from app.models import Product,Crud,Category,Tag,TagRelation,and_
from .. import admin


# 添加产品
@admin.route("/product/add", methods=['POST'])
@login_required
@auth_required
def product_add():
    data = request.form
    form = ProductForm(data)
    if form.validate():
        # 先添加产品信息  
        product_data = Crud.add(Product,data)
        if product_data:
            # 如果有标签信息，根据产品的id和标签ID保存关联的标签数据
            if data['tags']:
                tags = data['tags'].split(',') 
                tag_data = [TagRelation(
                    tag_type = 1,
                    relation_id = product_data.id,
                    tag_id =v
                ) for v in tags]
                Crud.add_all(tag_data)
            op_log("添加产品-%s" % product_data.title)
            return {"code": 1, "msg": "添加成功"}
        return {"code": 0, "msg": '添加失败，系统错误'}
    return {"code": 0, "msg": form.get_errors()}


# 产品列表
@admin.route("/product/list", methods=['GET'])
@login_required
@auth_required
def product_list():
    category_id = None
    page = 1
    search = ''
    if request.args.get('category_id'):
        category_id = int(request.args.get('category_id'))
    if request.args.get('page'):
        page = int(request.args.get('page'))
    if request.args.get('search'):
        search = request.args.get('search')
    #产品可用标签
    tag_data = Crud.get_data(Tag)
    #栏目树
    category_data = Crud.get_data(Category, Category.sort.desc())
    category_tree = build_tree(category_data, 0, 0)
    #产品栏目
    product_category = [v  for v in category_tree if v['type'] == 1 or v['type'] == 3 ]
    if category_id == None:
        product_data = Crud.search_data_paginate(Product,Product.title.like("%" + search + "%"),Product.sort.desc(),page,10)
    else:
        product_data = Crud.search_data_paginate(Product,and_(Product.category_id == category_id,Product.title.like("%" + search + "%")),Product.sort.desc(),page,10)
    return render_template("admin/product/product_list.html",
                           category_id=category_id,
                           product_data=product_data,
                           product_category = product_category,
                           tag_data = tag_data,
                           )


# 修改产品
@admin.route("/product/edit", methods=['GET', 'PUT'])
@login_required
@auth_required
def product_edit():
    if request.method == 'GET':
        getdata = request.args
        data = Crud.get_data_by_id(Product, getdata["id"])
        product_data = object_to_dict(data)
        #替换掉产品数据里面的TAGS
        tags = Crud.search_data(TagRelation,and_(TagRelation.relation_id==getdata["id"] , TagRelation.tag_type == 1),'create_time')
        if tags:
            product_data['tags'] = [v.tag_id for v in tags]
        return {"code": 1, "data": product_data}
    elif request.method == "PUT":
        data = request.form
        form = ProductForm(data)
        if form.validate():
            #移除已保存的tag
            tags = Crud.search_data(TagRelation,and_(TagRelation.relation_id==data["id"] , TagRelation.tag_type == 1),'create_time')
            if tags:
                del_tags = Crud.clean_all(tags)
            #保存修改后的信息
            result = Crud.update(Product,data)
            # 如果有标签信息，根据产品的id和标签ID保存关联的标签数据
            if data['tags']:
                tags = data['tags'].split(',') 
                tag_data = [TagRelation(
                    tag_type = 1,
                    relation_id = data["id"],
                    tag_id =v
                ) for v in tags]
                Crud.add_all(tag_data)
            if result:
                op_log("修改产品 #%s" %  data["id"])
                return {"code": 1, "msg": '修改成功'}
            return {"code": 0, "msg": '修改失败，系统错误'} 
        return {"code": 0, "msg": form.get_errors()}


# 删除产品
@admin.route("/product/del", methods=['DELETE'])
@login_required
@auth_required
def product_del():
    deldata = request.form
    data = Product.query.filter_by(id=deldata['id']).first_or_404()
    result = Crud.delete(data)
    if result:
        op_log("删除产品-%s" % data.title)
        return {"code": 1, "msg": '删除成功'}
    return {"code": 0, "msg": '删除失败'}    

app/home/__init__.py
# -*- coding: utf-8 -*- 
# Created by xuannan on 2019-01-01.
#导入蓝图模块
from flask import Blueprint
home = Blueprint("home",__name__)
import app.home.views.index
import app.home.views.base

app/home/views/__init__.py
# -*- coding: utf-8 -*- 
# Created by xuannan on 2019-01-01.

from flask import request,current_app,session
from app.expand.utils import build_tree,object_to_dict,set_qrcode
from app.models import Crud,Category,Conf,Ad,Product,Tag,Template
from .. import home
from app.extensions import cache

# cache的运行数量，通过request来进行不同cache的计数
CLICKS_COUNT = {}

class seoData(object):
    def __init__(self, keywords='',description='',title=''):
        self.keywords = keywords
        self.description = description
        self.title = title

#获取当前栏目的最上级栏目
def getTopColumn(data,id):
    for v in data:
        if v.id == int(id):
            if int(v.pid) == 0:
                return v
            return getTopColumn(data,v.pid)
        return

def make_cache_key(*args, **kwargs):
    """Cache的动态参数."""

    path = request.path
    args = str(hash(frozenset(request.args.items())))
    return (path + args).encode('utf-8')



# 上下文处理器
@home.context_processor
def tpl_extra():
    url =request.url
    ip=request.remote_addr
    webconfig = getWebConfig()
    current_app.logger.info("【%s】【%s】-%s"%(ip,session.get('user_email'),url))
    # 生成页面二维码
    url_code = getQrcode(url)
    data = dict(
        navs = getNavs(),
        webconfig = webconfig,
        url_code = url_code,
    )
    return data

# 点击数计算
@home.route("/click_count", methods=['GET'])
def click_count():
    if ('url' in request.args) and (request.args['url']):
        url = request.args['url']
        if url in CLICKS_COUNT:
            CLICKS_COUNT[url] += 1
        else:
            CLICKS_COUNT[url] = 0
    return 'count+1'


@cache.cached(timeout=600, key_prefix='webconfig')
def getWebConfig():
    '''
    获取站点配置信息
    '''
    webconfig = {}
    conf_model_data = Crud.get_data(Conf,Conf.sort.desc())
    for v in conf_model_data:
        webconfig[v.ename] = v.default_value
    return webconfig



@cache.cached(timeout=600, key_prefix='navs')
def getNavs():
    '''
    获取菜单
    '''
    category_data = getCategory()
    navs_data = [v for v in category_data if v.is_nav == 1]
    return build_tree(navs_data, 0, 0)


@cache.cached(timeout=600, key_prefix='categorys')
def getCategory():
    '''
    获取全部栏目
    '''
    return Crud.get_data(Category,Category.sort.desc())



@cache.cached(timeout=600, key_prefix='template')
def getWebTemplate():
    '''
    网站模板配置
    '''
    webconfig = getWebConfig()
    template = 'default'
    if 'templates' in webconfig:
        if webconfig['templates']:
            template = webconfig['templates']
    return template


@cache.cached(timeout=600, key_prefix='templates')
def getTemplates():
    '''
    获取网站模板页面设置
    '''
    return Crud.get_data(Template,Template.sort.desc())


@cache.cached(timeout=600, key_prefix='tags')
def getTag():
    '''
    获取标签信息
    '''
    return Crud.get_data(Tag,Tag.sort.desc())


def getQrcode(url):
    try:
        return set_qrcode(url)
    except Exception as err:
        print(err)
        return False

app/home/views/articles.py
# -*- coding: utf-8 -*- 
# Created by xuannan on 2019-01-01.
#从当前模块__init__导入蓝图对象
from . import home,seoData,cache,make_cache_key,CLICKS_COUNT
from app.models import Crud,Category,Article,Tag,Admin
from  app.models.base import db
from flask import render_template, redirect, url_for,flash,session,request
from sqlalchemy import or_,and_
import logging



@home.route("/articles/<int:nav_id>", methods=['GET'])
@home.route("/articles", methods=['GET'])
@cache.cached(timeout=60, key_prefix=make_cache_key)
def articles(nav_id=None):
    if nav_id==None:
        return redirect(url_for('home.index'))
    #参数转为字典
    request_data = request.args.to_dict()
    if request.args.get('page'):
        page = int(request.args.get('page'))
    else:
        page = 1
    param = []
    #栏目筛选，当前栏目的所有子栏目
    articles_column = Crud.search_data(Category,Category.pid == nav_id)
    articles_column_ids = [v.id for v in articles_column]
    articles_column_ids.append(nav_id)
    param.append(Article.column_id.in_(articles_column_ids))

    #根据搜索条件筛选
    if ('search' in request.args) and (request.args['search']):
        search = request.args['search']
        param.append(or_(Article.title.like("%" + search + "%"),Article.info.like("%" + search + "%"),Article.content.like("%" + search + "%")))
    #根据标签筛选
    if ('tag' in request.args) and (request.args['tag']):
        tag = request.args['tag']
        param.append(article_tag.c.tag_id == tag)
        param.append(Article.is_del == 0)
        articles = Article.query.join(article_tag).filter(*param).order_by(Article.sort.desc()).paginate(page,4)
    else:
        articles = Crud.search_data_paginate(Article,param,Article.sort.desc(),page,4)
        #articles = db.session.query(Article,Admin).join(Admin,Article.admin_id == Admin.id).filter(*param).order_by(Article.sort.desc()).paginate(page,4)
    return render_template(
        "home/articles.html",
        request_data = request_data,
        seo_data = seo_data,
        articles = articles
    )
#文章详情
@home.route("/article/<int:nav_id>/<int:id>", methods=['GET'])
@cache.memoize(60)
def article(nav_id=None,id=None):
    rule = str(request.path)
    if id==None or nav_id==None:
        return redirect(url_for('home.index'))
    #如果在详情页搜索
    if ('search' in request.args) and (request.args['search']):
        search = request.args['search']
        return redirect(url_for('home.articles',nav_id = nav_id,search = search))
    #获取产品的详细信息
    article_detail = Crud.get_data_by_id(Article,id)
    #如果点击量为None，赋值0
    if not article_detail.click:
            article_detail.click = 0
    #如果有缓存的点击量，更新点击量
    if rule in CLICKS_COUNT:
        article_detail.click = int(article_detail.click) + int(CLICKS_COUNT[rule])
    else:
        article_detail.click = int(article_detail.click)+1
    Crud.easy_update(article_detail)
    # 如果进行了非法操作
    if article_detail.column_id != nav_id:
         return redirect(url_for('home.index'))
    #获取标签作为关键词
    keywords = ','.join([v.name for v in article_detail.tags])

    #SEO信息
    seo_data.keywords =  keywords
    seo_data.description = article_detail.description
    seo_data.title = article_detail.title
    return render_template(
        "home/article.html",
        article_data=article_detail,
        seo_data = seo_data,
        )

app/home/views/pages.py
# -*- coding: utf-8 -*- 
# Created by xuannan on 2019-03-24.
__author__ = 'Allen xu'
from flask import render_template, request,jsonify
from app.expand.mail import MailObj,send_email
from app.home.forms import MessageForm
from app.models import Crud, Category,Message
from . import home,seo_data,cache

@home.route("/contact/<int:nav_id>", methods=['GET'])
@home.route("/contact", methods=['GET'])
@cache.memoize(60)
def contact(nav_id=None):
    return render_template('home/contact.html',
                           seo_data =seo_data,
                           )

@home.route("/about/<int:nav_id>", methods=['GET'])
@home.route("/about", methods=['GET'])
@cache.memoize(60)
def about(nav_id=None):
    return render_template('home/about.html',
                           seo_data =seo_data,
                           )

@home.route("/message", methods=['POST'])
def message():
    data = request.form
    form = MessageForm(data)
    ip = request.remote_addr
    # request 数据转为dict
    dict_data = data.to_dict()
    dict_data['ip'] = ip
    if form.validate():
        message_data = Crud.add(Message,dict_data)
        if message_data:
            re_mail = MailObj()
            re_mail.recipients.append(message_data.email)
            send_email(re_mail)
            warn_mail = MailObj()
            warn_mail.subject = '您有新的询盘，请注意查收！'
            warn_mail.html_body = '<p>姓名：%s</p>' \
                                '<p>邮箱：%s</p>' \
                                '<p>联系方式：%s</p>' \
                                '<p>留言内容：%s</p>' \
                                '<p>用户来源：%s</p>'% (message_data.name, message_data.email,message_data.contact,message_data.info,message_data.ip)
            send_email(warn_mail)
            return {"code":1, "msg": "Message submitted successfully, thank you for your support, we will contact you as soon as possible!"}
        return {"code": 0, "msg": 'System error, message submitted failure, please call our phone.'}
    return {"code": 0, "msg": form.get_errors()}
   

app/templates/home/about.html
{% extends "home/home.html" %}
{% block content %}
<!-- product_banner start -->
<div class="section parallax dark-translucent-bg" style=" background-image: url('{{active_nav.cover}}');">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ol class="breadcrumb breadcrumb-banner">
                    <li><i class="fa fa-home pr-10"></i><a href="{{url_for('home.index')}}">Home</a></li>
                    {% if top_nav.id == active_nav.id%}
                    <li class="active">{{active_nav.name}}</li>
                    {% else %}
                    <li><a href="{{top_nav.url+'/'+top_nav.id |string}}">{{top_nav.name}}</a></li>
                    <li class="active">{{active_nav.name}}</li>
                    {% endif %}
                </ol>
                <div class="separator-2"></div>
                {{active_nav.info | safe}}
            </div>
        </div>
    </div>
</div>
</div>
<!-- product_banner end -->

<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
       <div class="row">
								<div class="col-lg-3 col-sm-4">
									<div class="box-style-1 gray-bg team-member">
										<div class="overlay-container">
											<img src="{{active_nav.cover}}" alt="{{active_nav.name}}">
											<div class="overlay">
												<ul class="social-links colored clearfix">
													{% for v in columns.social_tools.children%}
                                                    <li class="{{v.name}}"><a target="_blank" href="{{v.href}}"><i class="fa {{v.icon}}"></i></a></li>
                                                    {% endfor %}
												</ul>
											</div>
										</div>
									</div>
								</div>
								<div class="col-lg-5 col-sm-8">
									{{active_nav.content | safe}}
								</div>
								<div class="col-lg-4 col-md-12 col-sm-8 col-sm-offset-4 col-md-offset-0">
									<div class="vertical-divider-left-lg side">
										<h2 class="title">Contact Us</h2>
										<ul class="list-icons">
											<li><i class="fa fa-map-marker pr-5"></i>{{webconfig.address}}</li>
											<li><i class="fa fa-phone pr-5"></i>{{webconfig.phone}}</li>
											<li><i class="fa fa-envelope pr-5"></i><a href="mailto:{{webconfig.email}}">{{webconfig.email}}</a></li>
										</ul>
										<ul class="social-links colored clearfix">
                                            {% for v in columns.social_tools.children%}
											<li class="{{v.name}}"><a target="_blank" href="{{v.href}}"><i class="fa {{v.icon}}"></i></a></li>
                                            {% endfor %}
										</ul>
									</div>
								</div>
							</div>
    </div>
</section>
<!-- main-container end -->
{% endblock %}
{% block js %}
<script>
    enterSearch('input[name=productsSearch]')

</script>
{% endblock %}

app/templates/home/article.html
{% extends "home/home.html" %}
{% block content %}
<!-- product_banner start -->
<div class="section parallax dark-translucent-bg" style=" background-image: url('{{active_nav.cover}}');">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ol class="breadcrumb breadcrumb-banner">
                    <li><i class="fa fa-home pr-10"></i><a href="{{url_for('home.index')}}">Home</a></li>
                    {% if top_nav.id == active_nav.id%}
                    <li class="active">{{active_nav.name}}</li>
                    {% else %}
                    <li><a href="{{top_nav.url+'/'+top_nav.id |string}}">{{top_nav.name}}</a></li>
                    <li class="active">{{active_nav.name}}</li>
                    {% endif %}
                </ol>
                <div class="separator-2"></div>
                {{active_nav.info | safe}}
            </div>
            <div class="col-md-4" style="margin-top: 30px">
                <div class="input-group form-group">
                    <input type="text" name="articlesSearch" class="form-control pull-right" placeholder="Search...">
                    <div class="input-group-addon" onclick="btnSearch(this)">
                        <i class="fa fa-search"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<!-- product_banner end -->

<!-- main-container start -->
<!-- ================ -->
<section class="main-container">

    <div class="container">
        <div class="row">

            <!-- main start -->
            <!-- ================ -->
            <div class="main col-md-8">

                <!-- page-title start -->
                <!-- ================ -->
                <h1 class="page-title margin-top-clear">{{article_data.title}}</h1>
                <!-- page-title end -->
                <!-- pictures panes start-->
                <div class="owl-carousel content-slider-with-controls">
                    <div class="overlay-container">
                        <img src="{{article_data.cover}}" alt="{{article_data.title}}">
                    </div>
                </div>
                <div class="product-interaction clearfix">
                    <ul class="links pull-left">
                        <li><i class="fa fa-tags pr-5"></i>
                            {% for v in article_data.tags %}
                            <a href="{{url_for('home.articles',nav_id=top_nav.id,tag=v.id)}}">{{v.name}} </a>
                            {% endfor %}
                        </li>
                    </ul>
                </div>
                <div class="col-md-12">
                    <p>{{article_data.info|safe}}</p>
                     <hr>
                    {{article_data.content | safe}}
                </div>

                <!-- pictures panes end-->
            </div>
            <aside class="col-md-4">
                <div class="sidebar">
                    <div class="portfolio-item side vertical-divider-left">
                        <div class="row">
                            <div class="col-md-12">
										<h2 class="title">Contact Us</h2>
										<ul class="list-icons">
											<li><i class="fa fa-phone pr-5"></i>{{webconfig.phone}}</li>
											<li><i class="fa fa-envelope pr-5"></i><a href="mailto:{{webconfig.email}}">{{webconfig.email}}</a></li>
										</ul>
										<ul class="social-links colored clearfix">
                                            {% for v in columns.social_tools.children%}
											<li class="{{v.name}}"><a target="_blank" href="{{v.href}}"><i class="fa {{v.icon}}"></i></a></li>
                                            {% endfor %}
										</ul>
                                 <hr>
								</div>
                            <div class="col-md-12">
                                <div class="clearfix">
                                    <h2 class="title margin-top-clear">Share This</h2>
                                    <ul class="list">
                                        <li><strong class="vertical-divider">URL </strong> <a
                                                href="{{ request.url }}">{{ request.url }}</a></li>
                                    </ul>
                                    <div class="qrcode">
                                        <img src="data:image/png;base64,{{url_code}}">
                                        <p>[ Open on Mobile ]</p>
                                    </div>
                                </div>
                                <hr>
                            </div>
                            <!-- Add the extra clearfix for only the required viewport -->
                            <div class="col-md-12">
                                <div class="clerfix">
                                    <h2 class="title margin-top-clear">Get more information</h2>
                                    <p>Leave your mailbox and we will send you the details of the article.</p>
                                    <form role="form" id="getMoreInfo">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                        <input type="hidden" name="name"/>
                                        <input type="hidden" name="contact"/>
                                        <textarea style="display: none" class="form-control" rows="2" name="info">
                                            <p>Interested : <h1>{{article_data.title}}</h1></p>
                                            <p>URL: <a href="{{ request.url }}">{{ request.url }}</a></p>
                                        </textarea>
                                        <div class="form-group has-feedback">
                                            <input type="email" class="form-control" placeholder="Email" name="email">
                                            <i class="fa fa-envelope-o form-control-feedback"></i>
                                        </div>
                                        <a onclick="sendMessage(this,'getMoreInfo')"
                                           class="btn btn-default">Subscribe</a>
                                    </form>
                                </div>
                                <hr>
                            </div>
                        </div>
                    </div>
                </div>
            </aside>


            <!-- main end -->


        </div>
    </div>
</section>
<!-- main-container end -->
{% endblock %}
{% block js %}
<script>
    enterSearch('input[name=articlesSearch]')
    click_count()
</script>
{% endblock %}

app/templates/home/articles.html
{% extends "home/home.html" %}
{% import "home/pagination.html" as pagination %}
{% block content %}
<!-- product_banner start -->
<div class="section parallax dark-translucent-bg" style=" background-image: url('{{active_nav.cover}}');">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ol class="breadcrumb breadcrumb-banner">
					<li><i class="fa fa-home pr-10"></i><a href="{{url_for('home.index')}}">Home</a></li>
                    {% if top_nav.id == active_nav.id%}
                    <li class="active">{{active_nav.name}}</li>
                    {% else %}
					<li><a href="{{top_nav.url+'/'+top_nav.id |string}}">{{top_nav.name}}</a></li>
					<li class="active">{{active_nav.name}}</li>
                    {% endif %}
				</ol>
                <div class="separator-2"></div>
                {{active_nav.info | safe}}
            </div>
             <div class="col-md-4" style="margin-top: 30px">
                    <div class="input-group form-group">
                        <input type="text" name="articlesSearch" class="form-control pull-right" placeholder="Search..." value="{{request_data.search}}">
                        <div class="input-group-addon"  onclick="btnSearch(this)">
                            <i class="fa fa-search"></i>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>
</div>
<!-- product_banner end -->

<!-- product start -->
<div class="section  clearfix object-non-visible animated object-visible fadeInUpSmall"
     data-animation-effect="fadeInUpSmall" data-effect-delay="300">
    <div class="container">
        <div class="row">
           <div class="main col-md-12">
               {% for v in articles.items%}
							<article class="clearfix blogpost object-non-visible animated object-visible fadeInUpSmall" data-animation-effect="fadeInUpSmall" data-effect-delay="200">
								<div class="blogpost-body">
									<div class="post-info">
										<span class="day">{{v.addtime.strftime('%d')}}</span>
										<span class="month">{{v.addtime.strftime('%m/%y')}}</span>
									</div>
									<div class="blogpost-content">
										<header>
											<h2 class="title"><a href="{{url_for('home.article',nav_id=active_nav.id,id=v.id)}}">{{v.title}}</a></h2>
										</header>
										<p>{{v.info|safe}}</p>
									</div>
								</div>
								<footer class="clearfix">
									<ul class="links pull-left">
										<li><i class="fa fa-tags pr-5"></i>
                                            {% for v in v.tags %}
                                            <a href="{{url_for('home.articles',nav_id=top_nav.id,tag=v.id)}}"> {{v.name}} </a>
                                            {% endfor %}
                                        </li>
									</ul>
									<a class="pull-right link" href="{{url_for('home.article',nav_id=active_nav.id,id=v.id)}}"><span>Read more</span></a>
								</footer>
							</article>
               {% endfor%}
               {{ pagination.page(articles,"home.articles",nav_id=active_nav.id,tag=request_data.tag,search=request_data.search) }}
						</div>
        </div>
    </div>

</div>
<!-- product end -->
{% endblock %}
{% block js %}
<script>
    enterSearch('input[name=articlesSearch]')
</script>
{% endblock %}